name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.10.0]
    steps:
    - name: 远程
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.myhost }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd app/JJLAZY.github.io
          git reset --hard
          git pull
          hexo g
          unalias cp
          cp -rf public/* ../blog/
