name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.10.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      with:
          # Private Key
        SSH_PRIVATE_KEY: q
    # Remote host
        REMOTE_HOST: q
    # Remote user
        REMOTE_USER: root
    # Source directory
        SOURCE: 2
    # Target directory
        TARGET: 2
